# Numpy

In [1]:
import numpy as np

In [2]:
python_list = [1, 2, 'arr', bool, False, 6.9]
print(python_list)

[1, 2, 'arr', <class 'bool'>, False, 6.9]


In [3]:
numpy_array = np.array([1, 2, 3, 4, 5])
print(numpy_array)

[1 2 3 4 5]


## Difference between numpy array & python list
**Data type:** Lists allow mixed types, NumPy arrays enforce a single type.  
**Performance:** NumPy arrays are faster and memory-efficient than lists.  
**Operations:** Lists need loops, arrays support vectorized element-wise ops.  
**Functionality:** NumPy provides rich math/stat functions, lists don’t.  
**Dimensions:** Lists use nesting for 2D/3D, arrays natively support n-D.

In [4]:
#Operations
lst = [1, 2, 3]
arr = np.array([1, 2, 3])

# Multiply each element by 2
# print([x*2 for x in lst])  # [2, 4, 6]  (list needs loop)
# print(arr * 2)             # [2 4 6]    (array direct)

#Functionality
arr = np.array([1, 2, 3])

# print(sum(arr))    # 6   (Python sum, works on lists too)
# print(arr.mean())  # 2.0 (NumPy extra power)
# print(arr.std())   # 0.816... (NumPy built-in stats)

## ndim

In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print('Dimension:', arr.ndim)
print('Shape:', arr.shape)

Dimension: 2
Shape: (2, 3)


## np.zeros

In [6]:
# Create numpy array with zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## np.ones

In [7]:
# Create numpy array with ones
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## np.empty

In [8]:
# Creates an array of given shape with random values from memory, without initializing them.
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## np.full

In [9]:
# Creates an array fixed constant value provided
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

## np.eye

In [15]:
# Creates a digonal array
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

## np.arange

In [11]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

## np.linspace

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## np.identity

In [16]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
# Create array of random floats between 0 and 1
np.random.rand(3, 3)

array([[0.23349741, 0.04585029, 0.4923591 ],
       [0.61952541, 0.05136078, 0.44307219],
       [0.1403976 , 0.06938109, 0.74014368]])